import type { Metadata } from 'next';
import { firaGo, helvetica, helveticaNeue } from './fonts/fonts';
import './globals.css';
import Header from './components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={`${firaGo.variable} ${helvetica.variable} ${helveticaNeue.variable}} antialiased`}
      >
        <Header />
        <div className="px-1 md:px-2 2xl:px-3">{children}</div>
      </body>
    </html>
  );
};

export default RootLayout;
